spring:
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/aisys_library?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false}
    username: ${MYSQL_USER:aisys}
    password: ${MYSQL_PASSWORD:aisys}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  h2:
    console:
      enabled: false
