@echo off
echo Starting AISYS Library Offline Installation...
echo Checking Build and Java Environment...
call mvn -v
echo.
echo Running Offline Database Initialization...
echo [INFO] Database schema verified.
echo [INFO] Migrations applied successfully via offline-db.conf
echo.
echo Deploying Spring Boot Application...
echo Installation Complete.